name: End-to-end tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-latest  # Updated to latest Ubuntu version (16.04 is outdated)

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Updated to v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v3  # Updated to v3
        with:
          start: npm run dev
